version: "3"

services:

  node0:
    build: .
    image: main 
    ports:
        - "10000:10000"
    environment:
      PEERS: 'node1,node2'
      NAME: 'node0'

  node1:
    image: main 
    ports:
        - "10001:10000"
    environment:
      PEERS: 'node0'
      NAME: 'node1'

  node2:
    image: main 
    ports:
        - "10002:10000"
    environment:
      PEERS: 'node0'
      NAME: 'node2'
